name: vixen_shell
description: Vixen's production Flutter shell and isolated native browser bridge.
publish_to: 'none'
version: 0.1.7+7

environment:
  sdk: ^3.14.0-28.0.dev
  flutter: '>=3.47.0-1.0.pre-160'

dependencies:
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  yaru: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    linux-gtk-default: gtk4
  uses-material-design: true
